export const CHECKLIST_ITEMS = [
  "Verificação do nível e troca de óleo do motor",
  "Verificação dos filtros de ar, óleo e combustível",
  "Correias e mangueiras (inspeção de rachaduras ou vazamentos)",
  "Sistema de injeção e escapamento",
  "Nível do fluido de freio",
  "Freio de estacionamento (manete)",
  "Sistema de suspensão (amortecedores, molas, barras estabilizadoras)",
  "Terminais de direção e folgas",
  "Calibragem, sulcos e estado geral dos pneus",
  "Alinhamento e balanceamento",
  "Aperto das porcas de roda",
  "Funcionamento de faróis, setas, luzes de freio e ré",
  "Bateria e conexões",
  "Painel de instrumentos e módulos",
  "Ar-condicionado e sistema de aquecimento",
  "Limpadores e esguichos de para-brisa",
  "Cintos de segurança e saídas de emergência",
  "Higienização interna",
  "PASTILHAS FRENTE",
  "DISCO FRENTE",
  "PASTILHAS TRAS",
  "DISCO TRAS"
];
